// Generated by `pracht typegen`. Do not edit manually.
import "@pracht/core";
import type { ApiRouteMethodMap, RouteLoaderData, RouteParamInput, SearchParamsInput } from "@pracht/core";

declare module "@pracht/core" {
  interface Register {
    routes: {
      "incident": {
        path: "/";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/incident")>;
      };
    };
    apiRoutes: {
      "/api/health": {
        path: "/api/health";
        params: Record<never, never>;
        methods: ApiRouteMethodMap<typeof import("./api/health")>;
      };
    };
  }
}

export {};
