// Generated by `pracht typegen`. Do not edit manually.
import { createHref } from "@pracht/core";
import type { HrefRouteDefinition } from "@pracht/core";

export const routes = [
  {
    id: "incident",
    path: "/",
  },
] as const satisfies readonly HrefRouteDefinition[];

export const href = createHref(routes);
